In [1]:
# Jupyter Notebook Version of the Resampling Script

# Import necessary libraries
from pathlib import Path
from multiprocessing import Pool
import logging
import pandas as pd
import numpy as np
import SimpleITK as sitk
import click
import matplotlib.pyplot as plt
import ipywidgets as widgets
from ipywidgets import interact
import os
import nibabel as nib

setup input and output folders

In [2]:
# Setting up logger to capture information and warnings
log_fmt = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
logging.basicConfig(level=logging.INFO, format=log_fmt)
logging.captureWarnings(True)
logger = logging.getLogger(__name__)

In [3]:
#  Function to get bounding boxes from CT and PT images
def get_bounding_boxes(ct, pt):
    """
    Get the bounding boxes of the CT and PT images.
    This works since all images have the same direction.
    """
    
    # Get the origins of both CT and PT images
    ct_origin = np.array(ct.GetOrigin())
    pt_origin = np.array(pt.GetOrigin())
    
    # Calculate the maximum positions for both CT and PT images
    ct_position_max = ct_origin + np.array(ct.GetSize()) * np.array(ct.GetSpacing())
    pt_position_max = pt_origin + np.array(pt.GetSize()) * np.array(pt.GetSpacing())
    
    # Return the combined bounding box that covers both images
    return np.concatenate([
        np.maximum(ct_origin, pt_origin),
        np.minimum(ct_position_max, pt_position_max),
    ], axis=0)

In [4]:
# Function to visualize CT data interactively
def show_ct_data(ct_data):
    # Ensure ct_data is a NumPy array
    ct_data = np.asarray(ct_data)
    
    # Define the function to plot a specific slice
    def plot_slice(slice_idx):
        plt.figure(figsize=(6, 6))
        plt.imshow(ct_data[:, :, slice_idx], cmap='gray')
        plt.title(f"Slice {slice_idx}")
        # plt.axis('off')
        plt.show()
    
    # Create an interactive slider to select slices
    interact(plot_slice, slice_idx=widgets.IntSlider(min=0, max=ct_data.shape[2] - 1, step=1, value=0))

In [5]:
# Function to visualize CT data with label contours interactively
def show_ct_data_with_labels(ct_data, label_data):
    """
    Display CT image slices with overlaid label contours interactively.

    Parameters:
    - ct_data: NumPy array of CT image data with shape (height, width, slices).
    - label_data: NumPy array of label data with the same shape as ct_data.
    """
    # Ensure ct_data and label_data are NumPy arrays
    ct_data = np.asarray(ct_data)
    label_data = np.asarray(label_data)
    
    # Verify that the shapes match
    if ct_data.shape != label_data.shape:
        raise ValueError("CT data and label data must have the same shape.")
    
    # Define the function to plot a specific slice
    def plot_slice(slice_idx):
        plt.figure(figsize=(6, 6))
        plt.imshow(ct_data[:, :, slice_idx], cmap='gray')
        
        # Overlay the label as a contour
        contours = plt.contour(label_data[:, :, slice_idx], levels=np.unique(label_data), colors='r', linewidths=0.5)
        
        # Optionally, add a colorbar or legend for labels
        # plt.clabel(contours, inline=True, fontsize=8)
        
        plt.title(f"Slice {slice_idx}")
        plt.axis('off')
        plt.show()
    
    # Create an interactive slider to select slices
    interact(plot_slice, slice_idx=widgets.IntSlider(min=0, max=ct_data.shape[2] - 1, step=1, value=0))

In [6]:
def apply_window(img, width=500, center=40, normal=True):
    img = np.asarray(img)
    # convert below window to black
    img[img<(center-(width/2))]=center-(width/2)
    # convert above window to white
    img[img>(center+(width/2))]=center+(width/2)

    if normal:
        # normalize image
        img_scaled = (img - np.min(img)) / (np.max(img) - np.min(img))
        # print(img_scaled.shape)
        # print(np.min(img_scaled), np.max(img_scaled))
        return img_scaled
    else:
        return img

# Start here

In [7]:
# Define paths for input images, labels, and output directories
# path_input_images = "../dataset/images"
# path_input_labels = "../dataset/labels"
# path_output_images = "../dataset/output/images"
# path_output_labels = "../dataset/output/labels"

path_input_images = "/Volumes/Seagate/Research/ADDA/original/images"
path_input_labels = "/Volumes/Seagate/Research/ADDA/original/labels"
path_output_images = "/Volumes/Seagate/Research/ADDA/resampled_subsets/images"
path_output_labels = "/Volumes/Seagate/Research/ADDA/resampled_subsets/labels"
path_data_breakdown = '../../datasets/ADDA/png_patches_2d/png_patch_training_file_with_tags.csv'

In [8]:
# Set the Paths to the 
input_image_folder = path_input_images
input_label_folder = path_input_labels
output_image_folder = path_output_images
output_label_folder = path_output_labels

cores = 12

resampling = (0.976562, 0.976562, 3.27)

# Resolve paths to absolute paths
input_image_folder = Path(input_image_folder).resolve()
input_label_folder = Path(input_label_folder).resolve()
output_image_folder = Path(output_image_folder).resolve()
output_label_folder = Path(output_label_folder).resolve()


print('Input image folder:', input_image_folder)
print('Input label folder:', input_label_folder)
print('Output image folder:', output_image_folder)
print('Output label folder:', output_label_folder)
print('Resampling voxel size:', resampling)

Input image folder: /Volumes/Seagate/Research/ADDA/original/images
Input label folder: /Volumes/Seagate/Research/ADDA/original/labels
Output image folder: /Volumes/Seagate/Research/ADDA/resampled_subsets/images
Output label folder: /Volumes/Seagate/Research/ADDA/resampled_subsets/labels
Resampling voxel size: (0.976562, 0.976562, 3.27)

## get the list of patient images to resample

1. load from input folder:

In [9]:
# Get list of patients by finding CT images in the input folder
# patient_list = [
#     f.name.split("__")[0] for f in input_image_folder.rglob("*_CT*")
# ]
# if len(patient_list) == 0:
#     raise ValueError("No patient found in the input folder")

# len(patient_list)
# patient_list

2. load from previous list of CSV file

we need to keep tabs of this file to create a new list later

In [10]:
df = pd.read_csv(path_data_breakdown)
df = df[['subject_id', 'dataset', 'set']]
df.head()

  subject_id dataset    set
0    MDA-039  source  train
1    MDA-039  source  train
2    MDA-039  source  train
3    MDA-039  source  train
4    MDA-039  source  train

In [11]:
df.groupby(['dataset', 'set']).subject_id.nunique().reset_index()

  dataset         set  subject_id
0  source        test          28
1  source       train         128
2  source  validation          28
3  target        test          15
4  target       train          50
5  target  validation           7

In [12]:
# remove duplicates
df = df[df.duplicated() == False].reset_index(drop=True)
df.head()

  subject_id dataset    set
0    MDA-039  source  train
1    MDA-192  source  train
2    MDA-187  source  train
3    MDA-179  source  train
4    MDA-162  source  train

In [13]:
df_dims = df.copy()

create a df to show the sizes of each image and their labels for analysis

In [14]:
# extract voxel size for the image
for i, sid in enumerate(df_dims['subject_id']):
#sid = 'MDA-179'
    img_path = os.path.join(input_image_folder, sid+'__CT.nii.gz')
    pt_path = os.path.join(input_image_folder, sid+'__PT.nii.gz')
    lbl_path = os.path.join(input_label_folder, sid+'.nii.gz')

    x = nib.load(img_path)
    x1 = nib.load(pt_path)
    x2 = nib.load(lbl_path)

    # get CT image data
    pixdim_x, pixdim_y, pixdim_z = x.header['pixdim'][1], x.header['pixdim'][2], x.header['pixdim'][3]
    dim_x, dim_y, dim_z = x.header['dim'][1], x.header['dim'][2], x.header['dim'][3]
    # save image dimensions
    df_dims.loc[df_dims['subject_id'] == sid, 'ct_dim_x'] = dim_x
    df_dims.loc[df_dims['subject_id'] == sid, 'ct_dim_y'] = dim_y
    df_dims.loc[df_dims['subject_id'] == sid, 'ct_dim_z'] = dim_z
    # save vovel dimensions
    df_dims.loc[df_dims['subject_id'] == sid, 'ct_pixdim_x'] = pixdim_x
    df_dims.loc[df_dims['subject_id'] == sid, 'ct_pixdim_y'] = pixdim_y
    df_dims.loc[df_dims['subject_id'] == sid, 'ct_pixdim_z'] = pixdim_z

    # Get Pet image dimenstion
    pixdim_x1, pixdim_y1, pixdim_z1 = x1.header['pixdim'][1], x1.header['pixdim'][2], x1.header['pixdim'][3]
    dim_x1, dim_y1, dim_z1 = x1.header['dim'][1], x1.header['dim'][2], x1.header['dim'][3]
    # save image dimensions
    df_dims.loc[df_dims['subject_id'] == sid, 'pt_dim_x'] = dim_x1
    df_dims.loc[df_dims['subject_id'] == sid, 'pt_dim_y'] = dim_y1
    df_dims.loc[df_dims['subject_id'] == sid, 'pt_dim_z'] = dim_z1
    # save vovel dimensions
    df_dims.loc[df_dims['subject_id'] == sid, 'pt_pixdim_x'] = pixdim_x1
    df_dims.loc[df_dims['subject_id'] == sid, 'pt_pixdim_y'] = pixdim_y1
    df_dims.loc[df_dims['subject_id'] == sid, 'pt_pixdim_z'] = pixdim_z1

    # Get Label image dimenstion
    pixdim_x2, pixdim_y2, pixdim_z2 = x2.header['pixdim'][1], x2.header['pixdim'][2], x2.header['pixdim'][3]
    dim_x2, dim_y2, dim_z2 = x2.header['dim'][1], x2.header['dim'][2], x2.header['dim'][3]
    # save image dimensions
    df_dims.loc[df_dims['subject_id'] == sid, 'lbl_dim_x'] = dim_x2
    df_dims.loc[df_dims['subject_id'] == sid, 'lbl_dim_y'] = dim_y2
    df_dims.loc[df_dims['subject_id'] == sid, 'lbl_dim_z'] = dim_z2
    # save vovel dimensions
    df_dims.loc[df_dims['subject_id'] == sid, 'lbl_pixdim_x'] = pixdim_x2
    df_dims.loc[df_dims['subject_id'] == sid, 'lbl_pixdim_y'] = pixdim_y2
    df_dims.loc[df_dims['subject_id'] == sid, 'lbl_pixdim_z'] = pixdim_z2

    # print counter 
    if i % 10 == 0:
        percentage = (i / len(df_dims['subject_id'])) * 100
        print(f'Round {i}: {percentage:.2f}% completed')

df_dims.head()

Round 0: 0.00% completed
Round 10: 3.91% completed
Round 20: 7.81% completed
Round 30: 11.72% completed
Round 40: 15.62% completed
Round 50: 19.53% completed
Round 60: 23.44% completed
Round 70: 27.34% completed
Round 80: 31.25% completed
Round 90: 35.16% completed
Round 100: 39.06% completed
Round 110: 42.97% completed
Round 120: 46.88% completed
Round 130: 50.78% completed
Round 140: 54.69% completed
Round 150: 58.59% completed
Round 160: 62.50% completed
Round 170: 66.41% completed
Round 180: 70.31% completed
Round 190: 74.22% completed
Round 200: 78.12% completed
Round 210: 82.03% completed
Round 220: 85.94% completed
Round 230: 89.84% completed
Round 240: 93.75% completed
Round 250: 97.66% completed

,subject_id,dataset,set,ct_dim_x,ct_dim_y,ct_dim_z,ct_pixdim_x,ct_pixdim_y,ct_pixdim_z,pt_dim_x,...,pt_dim_z,pt_pixdim_x,pt_pixdim_y,pt_pixdim_z,lbl_dim_x,lbl_dim_y,lbl_dim_z,lbl_pixdim_x,lbl_pixdim_y,lbl_pixdim_z
0,MDA-039,source,train,512.0,512.0,127.0,0.976562,0.976562,3.27,128.0,...,127.0,5.46875,5.46875,3.27,512.0,512.0,127.0,0.976562,0.976562,3.27
1,MDA-192,source,train,512.0,512.0,127.0,0.976562,0.976562,3.27,128.0,...,127.0,5.46875,5.46875,3.27,512.0,512.0,127.0,0.976562,0.976562,3.27
2,MDA-187,source,train,512.0,512.0,127.0,0.976562,0.976562,3.27,128.0,...,127.0,5.46875,5.46875,3.27,512.0,512.0,127.0,0.976562,0.976562,3.27
3,MDA-179,source,train,512.0,512.0,127.0,0.976562,0.976562,3.27,128.0,...,127.0,5.46875,5.46875,3.27,512.0,512.0,127.0,0.976562,0.976562,3.27
4,MDA-162,source,train,512.0,512.0,87.0,0.976562,0.976562,3.27,128.0,...,87.0,5.46875,5.46875,3.27,512.0,512.0,87.0,0.976562,0.976562,3.27

In [15]:
dim_cols = [
    'ct_dim_x', 'ct_dim_y',
    'pt_dim_x', 'pt_dim_y', 
    'lbl_dim_x', 'lbl_dim_y',
]

# Check if all rows have the same values across the selected columns
same_dims = df_dims[dim_cols].nunique(axis=1) == 1

# Output rows where dimensions are not the same (False means the dimensions vary in those rows)
inconsistent_rows = df_dims[~same_dims]

# Print the number of inconsistent rows and inspect them
print(f"Number of rows with inconsistent dimensions: {len(inconsistent_rows)}")
print(inconsistent_rows['subject_id'])

Number of rows with inconsistent dimensions: 256
0       MDA-039
1       MDA-192
2       MDA-187
3       MDA-179
4       MDA-162
         ...
251    CHUP-027
252    CHUP-030
253    CHUP-038
254    CHUP-052
255    CHUP-061
Name: subject_id, Length: 256, dtype: object

In [16]:
# find which pet iimages are not 128

df_dims[df_dims['pt_dim_x'] != 128]

,subject_id,dataset,set,ct_dim_x,ct_dim_y,ct_dim_z,ct_pixdim_x,ct_pixdim_y,ct_pixdim_z,pt_dim_x,...,pt_dim_z,pt_pixdim_x,pt_pixdim_y,pt_pixdim_z,lbl_dim_x,lbl_dim_y,lbl_dim_z,lbl_pixdim_x,lbl_pixdim_y,lbl_pixdim_z
13,MDA-113,source,train,512.0,512.0,134.0,0.976562,0.976562,2.80,256.0,...,134.0,2.734375,2.734375,2.800,512.0,512.0,134.0,0.976562,0.976562,2.80
21,MDA-120,source,train,512.0,512.0,407.0,0.976562,0.976562,3.27,192.0,...,407.0,3.645833,3.645833,3.270,512.0,512.0,408.0,0.976562,0.976562,3.27
39,MDA-114,source,train,512.0,512.0,119.0,0.976562,0.976562,3.27,192.0,...,119.0,3.645833,3.645833,3.270,512.0,512.0,119.0,0.976562,0.976562,3.27
51,MDA-112,source,train,512.0,512.0,119.0,0.976562,0.976562,3.27,256.0,...,119.0,2.734375,2.734375,3.270,512.0,512.0,119.0,0.976562,0.976562,3.27
53,MDA-117,source,train,512.0,512.0,335.0,0.976562,0.976562,3.27,192.0,...,335.0,3.645833,3.645833,3.270,512.0,512.0,335.0,0.976562,0.976562,3.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,CHUP-027,target,validation,512.0,512.0,736.0,0.976562,0.976562,1.50,200.0,...,543.0,4.072830,4.072830,2.027,512.0,512.0,736.0,0.976562,0.976562,1.50
252,CHUP-030,target,validation,512.0,512.0,736.0,0.976562,0.976562,1.50,200.0,...,543.0,4.072830,4.072830,2.027,512.0,512.0,736.0,0.976562,0.976562,1.50
253,CHUP-038,target,validation,512.0,512.0,568.0,0.976562,0.976562,1.50,200.0,...,419.0,4.072830,4.072830,2.027,512.0,512.0,568.0,0.976562,0.976562,1.50
254,CHUP-052,target,validation,512.0,512.0,568.0,0.976562,0.976562,1.50,200.0,...,419.0,4.072830,4.072830,2.027,512.0,512.0,568.0,0.976562,0.976562,1.50
255,CHUP-061,target,validation,512.0,512.0,652.0,0.976562,0.976562,1.50,200.0,...,481.0,4.072830,4.072830,2.027,512.0,512.0,652.0,0.976562,0.976562,1.50

In [17]:
df_dims[df_dims['subject_id']=='CHUP-030']

,subject_id,dataset,set,ct_dim_x,ct_dim_y,ct_dim_z,ct_pixdim_x,ct_pixdim_y,ct_pixdim_z,pt_dim_x,...,pt_dim_z,pt_pixdim_x,pt_pixdim_y,pt_pixdim_z,lbl_dim_x,lbl_dim_y,lbl_dim_z,lbl_pixdim_x,lbl_pixdim_y,lbl_pixdim_z
252,CHUP-030,target,validation,512.0,512.0,736.0,0.976562,0.976562,1.5,200.0,...,543.0,4.07283,4.07283,2.027,512.0,512.0,736.0,0.976562,0.976562,1.5

## Start resampling

In [19]:
# Main function to perform resampling
def main(patient, input_image_folder, input_label_folder, output_image_folder,
         output_label_folder, cores, resampling):
    """Resamples NIFTI files within the maximal bounding box covered by both modalities (PT and CT)."""
    
    logger.info('Resampling')

    # Resolve paths to absolute paths
    # input_image_folder = Path(input_image_folder).resolve()
    # input_label_folder = Path(input_label_folder).resolve()
    # output_image_folder = Path(output_image_folder).resolve()
    # output_label_folder = Path(output_label_folder).resolve()

    # Create output folders if they do not exist
    # output_image_folder.mkdir(exist_ok=True)
    # output_label_folder.mkdir(exist_ok=True)
    # print('Resampling with voxel size: {}'.format(resampling))

    # Get list of patients by finding CT images in the input folder
    # patient_list = [
    #     f.name.split("__")[0] for f in input_image_folder.rglob("*_CT*")
    # ]
    # if len(patient_list) == 0:
    #     raise ValueError("No patient found in the input folder")

    # print(patient_list)
    
    # Initialize the resampler with default settings
    resampler = sitk.ResampleImageFilter()
    resampler.SetOutputDirection([1, 0, 0, 0, 1, 0, 0, 0, 1])
    resampler.SetOutputSpacing(resampling)

    # Define the function to resample one patient's images and labels
    def resample_one_patient(p):
        # Read CT and PT images for the patient
        ct = sitk.ReadImage(str([f for f in input_image_folder.rglob(p + "__CT*")][0]))
        pt = sitk.ReadImage(str([f for f in input_image_folder.rglob(p + "__PT*")][0]))
        
        # Read label images for the patient
        labels = [(sitk.ReadImage(str(f)), f.name) for f in input_label_folder.glob(p + "*")]
        
        # Get bounding box for the resampling operation
        bb = get_bounding_boxes(ct, pt)
        size = np.round((bb[3:] - bb[:3]) / resampling).astype(int)
        
        # Configure resampler settings for CT and PT images
        resampler.SetOutputOrigin(bb[:3])
        resampler.SetSize([int(k) for k in size])
        resampler.SetInterpolator(sitk.sitkBSpline)  # Use cubic spline interpolation for CT and PT
        
        # Resample CT and PT images
        ct = resampler.Execute(ct)
        pt = resampler.Execute(pt)
        
        # # # Save the resampled CT and PT images to the output folder
        # sitk.WriteImage(ct, str((output_image_folder / (p + "__CT.nii.gz"))))
        # sitk.WriteImage(pt, str((output_image_folder / (p + "__PT.nii.gz"))))
        
        # Configure resampler for label images using nearest neighbor interpolation
        resampler.SetInterpolator(sitk.sitkNearestNeighbor)
        for label, name in labels:
            label = resampler.Execute(label)
            # sitk.WriteImage(label, str((output_label_folder / name)))
        
        return ct, pt, label

    # # Loop through each patient and resample their images and labels
    # for p in patient_list:
    #     resample_one_patient(p)
    # # Uncomment for parallel processing to speed up the operation
    # # with Pool(cores) as p:
    # #     p.map(resample_one_patient, patient_list)

    ct_res, pet_res, lbl_res = resample_one_patient(patient)
    return ct_res, pet_res, lbl_res

In [20]:
def process_patient(patient, input_image_folder, input_label_folder, output_image_folder, output_label_folder, cores, resampling):
    """
    Processes a single patient's CT, PET, and label images, applies a window function, 
    and rotates them 90 degrees.
    
    Args:
    - patient (str): Identifier for the patient to process.
    - input_image_folder (str): Path to the folder containing the input images.
    - input_label_folder (str): Path to the folder containing the input labels.
    - output_image_folder (str): Path to the folder where processed images will be saved.
    - output_label_folder (str): Path to the folder where processed labels will be saved.
    - cores (int): Number of cores to use for processing.
    - resampling (str): Resampling parameter.

    Returns:
    - (tuple): Rotated and processed CT, PET, and label arrays.
    """
    # Call the main function to start resampling (one patient)
    c, p, l = main(patient, input_image_folder, input_label_folder, output_image_folder, output_label_folder, cores, resampling)

    # Convert images to NumPy arrays and apply windowing to CT image
    cn = apply_window(sitk.GetArrayFromImage(c))
    pn = sitk.GetArrayFromImage(p)
    ln = sitk.GetArrayFromImage(l)
    
    # Print the shapes for verification
    print(f"Patient: {patient}")
    # print("Shapes before rotation:", cn.shape, pn.shape, ln.shape)

    # Rotate the images by 90 degrees along (0, 2) axes
    pn_r = np.rot90(pn, axes=(0, 2))
    cn_r = np.rot90(cn, axes=(0, 2))
    ln_r = np.rot90(ln, axes=(0, 2))

    # Print the shapes after rotation for verification
    # print("Shapes after rotation:", cn_r.shape, pn_r.shape, ln_r.shape)
    
    # Return the rotated images
    return cn_r, pn_r, ln_r

In [21]:
for i, sid in enumerate(df_dims['subject_id']):
    # Process patient and get rotated images
    cn_r, pn_r, ln_r = process_patient(sid, input_image_folder, input_label_folder, output_image_folder, output_label_folder, cores, resampling)

    
    # optional 
    # show_ct_data_with_labels(cn_r, ln_r)
    print(cn_r.shape)
    # Convert rotated NumPy arrays back to SimpleITK Image objects
    cn_r_img = sitk.GetImageFromArray(np.transpose(cn_r, (2, 0, 1)))
    pn_r_img = sitk.GetImageFromArray(np.transpose(pn_r, (2, 0, 1)))
    ln_r_img = sitk.GetImageFromArray(np.transpose(ln_r, (2, 0, 1)))

    # Save the resampled CT and PT images to the output folder
    sitk.WriteImage(cn_r_img, str(output_image_folder / (sid + "__CT.nii.gz")))
    sitk.WriteImage(pn_r_img, str(output_image_folder / (sid + "__PT.nii.gz")))

    # Save the resampled Label to the output folder
    sitk.WriteImage(ln_r_img, str(output_label_folder / (sid + ".nii.gz")))


    # Print counter to show progress every 10 iterations
    if i % 10 == 0:
        percentage = (i / len(df_dims['subject_id'])) * 100
        print(f'Round {i}: {percentage:.2f}% completed')

    # Optional: break to limit the loop 
    # break

2024-11-11 18:49:07,325 - __main__ - INFO - Resampling

Patient: MDA-039
(512, 512, 127)

2024-11-11 18:49:16,527 - __main__ - INFO - Resampling

Round 0: 0.00% completed
Patient: MDA-192
(512, 512, 127)

2024-11-11 18:49:26,585 - __main__ - INFO - Resampling

Patient: MDA-187
(512, 512, 127)

2024-11-11 18:49:35,119 - __main__ - INFO - Resampling

Patient: MDA-179
(512, 512, 127)

2024-11-11 18:49:44,045 - __main__ - INFO - Resampling

Patient: MDA-162
(512, 512, 87)

2024-11-11 18:49:50,057 - __main__ - INFO - Resampling

Patient: MDA-097
(512, 512, 311)

2024-11-11 18:50:10,347 - __main__ - INFO - Resampling

Patient: MDA-194
(512, 512, 287)

2024-11-11 18:50:29,631 - __main__ - INFO - Resampling

Patient: MDA-095
(512, 512, 127)

2024-11-11 18:50:38,377 - __main__ - INFO - Resampling

Patient: MDA-038
(512, 512, 127)

2024-11-11 18:50:47,036 - __main__ - INFO - Resampling

Patient: MDA-147
(512, 512, 127)

2024-11-11 18:50:55,553 - __main__ - INFO - Resampling

Patient: MDA-150
(512, 512, 127)

2024-11-11 18:51:03,891 - __main__ - INFO - Resampling

Round 10: 3.91% completed
Patient: MDA-133
(512, 512, 127)

2024-11-11 18:51:12,531 - __main__ - INFO - Resampling

Patient: MDA-071
(512, 512, 127)

2024-11-11 18:51:20,873 - __main__ - INFO - Resampling

Patient: MDA-113
(512, 512, 115)

2024-11-11 18:51:29,643 - __main__ - INFO - Resampling

Patient: MDA-023
(512, 512, 127)

2024-11-11 18:51:38,223 - __main__ - INFO - Resampling

Patient: MDA-024
(512, 512, 127)

2024-11-11 18:51:46,679 - __main__ - INFO - Resampling

Patient: MDA-013
(512, 512, 91)

2024-11-11 18:51:52,931 - __main__ - INFO - Resampling

Patient: MDA-059
(512, 512, 311)

2024-11-11 18:52:14,097 - __main__ - INFO - Resampling

Patient: MDA-006
(512, 512, 223)

2024-11-11 18:52:29,727 - __main__ - INFO - Resampling

Patient: MDA-101
(512, 512, 287)

2024-11-11 18:52:49,730 - __main__ - INFO - Resampling

Patient: MDA-065
(512, 512, 127)

2024-11-11 18:52:58,265 - __main__ - INFO - Resampling

Round 20: 7.81% completed
Patient: MDA-120
(512, 512, 407)

2024-11-11 18:53:25,904 - __main__ - INFO - Resampling

Patient: MDA-163
(512, 512, 311)

2024-11-11 18:53:46,701 - __main__ - INFO - Resampling

Patient: MDA-064
(512, 512, 127)

2024-11-11 18:53:55,310 - __main__ - INFO - Resampling

Patient: MDA-025
(512, 512, 127)

2024-11-11 18:54:04,087 - __main__ - INFO - Resampling

Patient: MDA-088
(512, 512, 127)

2024-11-11 18:54:12,486 - __main__ - INFO - Resampling

Patient: MDA-098
(512, 512, 127)

2024-11-11 18:54:21,269 - __main__ - INFO - Resampling

Patient: MDA-099
(512, 512, 127)

2024-11-11 18:54:29,939 - __main__ - INFO - Resampling

Patient: MDA-078
(512, 512, 127)

2024-11-11 18:54:38,590 - __main__ - INFO - Resampling

Patient: MDA-020
(512, 512, 127)

2024-11-11 18:54:47,267 - __main__ - INFO - Resampling

Patient: MDA-100
(512, 512, 127)

2024-11-11 18:54:55,543 - __main__ - INFO - Resampling

Round 30: 11.72% completed
Patient: MDA-021
(512, 512, 127)

2024-11-11 18:55:04,064 - __main__ - INFO - Resampling

Patient: MDA-005
(512, 512, 267)

2024-11-11 18:55:22,330 - __main__ - INFO - Resampling

Patient: MDA-047
(512, 512, 127)

2024-11-11 18:55:30,973 - __main__ - INFO - Resampling

Patient: MDA-173
(512, 512, 91)

2024-11-11 18:55:37,088 - __main__ - INFO - Resampling

Patient: MDA-146
(512, 512, 87)

2024-11-11 18:55:43,217 - __main__ - INFO - Resampling

Patient: MDA-068
(512, 512, 127)

2024-11-11 18:55:51,760 - __main__ - INFO - Resampling

Patient: MDA-053
(512, 512, 127)

2024-11-11 18:56:00,059 - __main__ - INFO - Resampling

Patient: MDA-004
(512, 512, 223)

2024-11-11 18:56:15,012 - __main__ - INFO - Resampling

Patient: MDA-114
(512, 512, 119)

2024-11-11 18:56:23,106 - __main__ - INFO - Resampling

Patient: MDA-055
(512, 512, 311)

2024-11-11 18:56:44,530 - __main__ - INFO - Resampling

Round 40: 15.62% completed
Patient: MDA-061
(512, 512, 127)

2024-11-11 18:56:53,122 - __main__ - INFO - Resampling

Patient: MDA-132
(512, 512, 127)

2024-11-11 18:57:01,897 - __main__ - INFO - Resampling

Patient: MDA-164
(512, 512, 295)

2024-11-11 18:57:21,897 - __main__ - INFO - Resampling

Patient: MDA-159
(512, 512, 127)

2024-11-11 18:57:30,307 - __main__ - INFO - Resampling

Patient: MDA-172
(512, 512, 127)

2024-11-11 18:57:38,840 - __main__ - INFO - Resampling

Patient: MDA-143
(512, 512, 127)

2024-11-11 18:57:47,650 - __main__ - INFO - Resampling

Patient: MDA-175
(512, 512, 311)

2024-11-11 18:58:08,318 - __main__ - INFO - Resampling

Patient: MDA-076
(512, 512, 127)

2024-11-11 18:58:17,082 - __main__ - INFO - Resampling

Patient: MDA-139
(512, 512, 127)

2024-11-11 18:58:25,462 - __main__ - INFO - Resampling

Patient: MDA-018
(512, 512, 127)

2024-11-11 18:58:34,152 - __main__ - INFO - Resampling

Round 50: 19.53% completed
Patient: MDA-112
(512, 512, 119)

2024-11-11 18:58:42,466 - __main__ - INFO - Resampling

Patient: MDA-048
(512, 512, 311)

2024-11-11 18:59:03,149 - __main__ - INFO - Resampling

Patient: MDA-117
(512, 512, 335)

2024-11-11 18:59:25,699 - __main__ - INFO - Resampling

Patient: MDA-043
(512, 512, 127)

2024-11-11 18:59:34,598 - __main__ - INFO - Resampling

Patient: MDA-169
(512, 512, 91)

2024-11-11 18:59:40,568 - __main__ - INFO - Resampling

Patient: MDA-050
(512, 512, 127)

2024-11-11 18:59:49,123 - __main__ - INFO - Resampling

Patient: MDA-190
(512, 512, 311)

2024-11-11 19:00:10,043 - __main__ - INFO - Resampling

Patient: MDA-049
(512, 512, 127)

2024-11-11 19:00:18,311 - __main__ - INFO - Resampling

Patient: MDA-091
(512, 512, 127)

2024-11-11 19:00:26,696 - __main__ - INFO - Resampling

Patient: MDA-045
(512, 512, 127)

2024-11-11 19:00:34,984 - __main__ - INFO - Resampling

Round 60: 23.44% completed
Patient: MDA-067
(512, 512, 295)

2024-11-11 19:00:53,907 - __main__ - INFO - Resampling

Patient: MDA-058
(512, 512, 127)

2024-11-11 19:01:02,319 - __main__ - INFO - Resampling

Patient: MDA-134
(512, 512, 127)

2024-11-11 19:01:10,699 - __main__ - INFO - Resampling

Patient: MDA-082
(512, 512, 127)

2024-11-11 19:01:19,032 - __main__ - INFO - Resampling

Patient: MDA-148
(512, 512, 127)

2024-11-11 19:01:27,685 - __main__ - INFO - Resampling

Patient: MDA-027
(512, 512, 127)

2024-11-11 19:01:36,139 - __main__ - INFO - Resampling

Patient: MDA-011
(512, 512, 91)

2024-11-11 19:01:42,327 - __main__ - INFO - Resampling

Patient: MDA-121
(512, 512, 119)

2024-11-11 19:01:50,663 - __main__ - INFO - Resampling

Patient: MDA-144
(512, 512, 355)

2024-11-11 19:02:13,982 - __main__ - INFO - Resampling

Patient: MDA-156
(512, 512, 127)

2024-11-11 19:02:22,482 - __main__ - INFO - Resampling

Round 70: 27.34% completed
Patient: MDA-184
(512, 512, 127)

2024-11-11 19:02:31,043 - __main__ - INFO - Resampling

Patient: MDA-183
(512, 512, 127)

2024-11-11 19:02:39,453 - __main__ - INFO - Resampling

Patient: MDA-093
(512, 512, 127)

2024-11-11 19:02:48,038 - __main__ - INFO - Resampling

Patient: MDA-016
(512, 512, 135)

2024-11-11 19:02:56,993 - __main__ - INFO - Resampling

Patient: MDA-092
(512, 512, 311)

2024-11-11 19:03:18,029 - __main__ - INFO - Resampling

Patient: MDA-116
(512, 512, 119)

2024-11-11 19:03:26,627 - __main__ - INFO - Resampling

Patient: MDA-034
(512, 512, 311)

2024-11-11 19:03:48,557 - __main__ - INFO - Resampling

Patient: MDA-155
(512, 512, 127)

2024-11-11 19:03:56,847 - __main__ - INFO - Resampling

Patient: MDA-108
(512, 512, 318)

2024-11-11 19:04:16,623 - __main__ - INFO - Resampling

Patient: MDA-044
(512, 512, 127)

2024-11-11 19:04:25,133 - __main__ - INFO - Resampling

Round 80: 31.25% completed
Patient: MDA-083
(512, 512, 127)

2024-11-11 19:04:33,447 - __main__ - INFO - Resampling

Patient: MDA-089
(512, 512, 127)

2024-11-11 19:04:42,046 - __main__ - INFO - Resampling

Patient: MDA-118
(512, 512, 119)

2024-11-11 19:04:50,367 - __main__ - INFO - Resampling

Patient: MDA-041
(512, 512, 127)

2024-11-11 19:04:59,141 - __main__ - INFO - Resampling

Patient: MDA-046
(512, 512, 127)

2024-11-11 19:05:07,613 - __main__ - INFO - Resampling

Patient: MDA-040
(512, 512, 127)

2024-11-11 19:05:16,245 - __main__ - INFO - Resampling

Patient: MDA-007
(512, 512, 263)

2024-11-11 19:05:35,568 - __main__ - INFO - Resampling

Patient: MDA-110
(512, 512, 115)

2024-11-11 19:05:44,149 - __main__ - INFO - Resampling

Patient: MDA-069
(512, 512, 127)

2024-11-11 19:05:52,471 - __main__ - INFO - Resampling

Patient: MDA-109
(512, 512, 335)

2024-11-11 19:06:14,920 - __main__ - INFO - Resampling

Round 90: 35.16% completed
Patient: MDA-137
(512, 512, 127)

2024-11-11 19:06:23,982 - __main__ - INFO - Resampling

Patient: MDA-075
(512, 512, 327)

2024-11-11 19:06:46,834 - __main__ - INFO - Resampling

Patient: MDA-111
(512, 512, 298)

2024-11-11 19:07:06,786 - __main__ - INFO - Resampling

Patient: MDA-080
(512, 512, 127)

2024-11-11 19:07:16,882 - __main__ - INFO - Resampling

Patient: MDA-081
(512, 512, 127)

2024-11-11 19:07:26,864 - __main__ - INFO - Resampling

Patient: MDA-022
(512, 512, 87)

2024-11-11 19:07:34,115 - __main__ - INFO - Resampling

Patient: MDA-181
(512, 512, 127)

2024-11-11 19:07:44,345 - __main__ - INFO - Resampling

Patient: MDA-056
(512, 512, 327)

2024-11-11 19:08:10,642 - __main__ - INFO - Resampling

Patient: MDA-017
(512, 512, 87)

2024-11-11 19:08:17,637 - __main__ - INFO - Resampling

Patient: MDA-087
(512, 512, 311)

2024-11-11 19:08:42,400 - __main__ - INFO - Resampling

Round 100: 39.06% completed
Patient: MDA-012
(512, 512, 91)

2024-11-11 19:08:49,478 - __main__ - INFO - Resampling

Patient: MDA-174
(512, 512, 87)

2024-11-11 19:08:56,289 - __main__ - INFO - Resampling

Patient: MDA-042
(512, 512, 127)

2024-11-11 19:09:06,137 - __main__ - INFO - Resampling

Patient: MDA-030
(512, 512, 267)

2024-11-11 19:09:28,185 - __main__ - INFO - Resampling

Patient: MDA-191
(512, 512, 127)

2024-11-11 19:09:38,152 - __main__ - INFO - Resampling

Patient: MDA-182
(512, 512, 91)

2024-11-11 19:09:45,795 - __main__ - INFO - Resampling

Patient: MDA-085
(512, 512, 127)

2024-11-11 19:09:55,957 - __main__ - INFO - Resampling

Patient: MDA-166
(512, 512, 91)

2024-11-11 19:10:02,783 - __main__ - INFO - Resampling

Patient: MDA-054
(512, 512, 127)

2024-11-11 19:10:12,843 - __main__ - INFO - Resampling

Patient: MDA-131
(512, 512, 127)

2024-11-11 19:10:22,502 - __main__ - INFO - Resampling

Round 110: 42.97% completed
Patient: MDA-189
(512, 512, 135)

2024-11-11 19:10:32,816 - __main__ - INFO - Resampling

Patient: MDA-154
(512, 512, 127)

2024-11-11 19:10:42,571 - __main__ - INFO - Resampling

Patient: MDA-151
(512, 512, 127)

2024-11-11 19:10:52,904 - __main__ - INFO - Resampling

Patient: MDA-090
(512, 512, 91)

2024-11-11 19:11:00,290 - __main__ - INFO - Resampling

Patient: MDA-165
(512, 512, 127)

2024-11-11 19:11:09,669 - __main__ - INFO - Resampling

Patient: MDA-060
(512, 512, 127)

2024-11-11 19:11:18,309 - __main__ - INFO - Resampling

Patient: MDA-125
(512, 512, 106)

2024-11-11 19:11:27,016 - __main__ - INFO - Resampling

Patient: MDA-197
(512, 512, 127)

2024-11-11 19:11:35,309 - __main__ - INFO - Resampling

Patient: MDA-130
(512, 512, 127)

2024-11-11 19:11:43,664 - __main__ - INFO - Resampling

Patient: MDA-141
(512, 512, 127)

2024-11-11 19:11:51,902 - __main__ - INFO - Resampling

Round 120: 46.88% completed
Patient: MDA-188
(512, 512, 311)

2024-11-11 19:12:13,904 - __main__ - INFO - Resampling

Patient: MDA-200
(512, 512, 267)

2024-11-11 19:12:32,183 - __main__ - INFO - Resampling

Patient: MDA-199
(512, 512, 127)

2024-11-11 19:12:40,906 - __main__ - INFO - Resampling

Patient: MDA-051
(512, 512, 127)

2024-11-11 19:12:49,402 - __main__ - INFO - Resampling

Patient: MDA-062
(512, 512, 127)

2024-11-11 19:12:57,580 - __main__ - INFO - Resampling

Patient: MDA-128
(512, 512, 106)

2024-11-11 19:13:06,458 - __main__ - INFO - Resampling

Patient: MDA-102
(512, 512, 311)

2024-11-11 19:13:27,811 - __main__ - INFO - Resampling

Patient: MDA-103
(512, 512, 311)

2024-11-11 19:13:48,478 - __main__ - INFO - Resampling

Patient: MDA-010
(512, 512, 91)

2024-11-11 19:13:54,622 - __main__ - INFO - Resampling

Patient: MDA-161
(512, 512, 299)

2024-11-11 19:14:14,907 - __main__ - INFO - Resampling

Round 130: 50.78% completed
Patient: MDA-185
(512, 512, 127)

2024-11-11 19:14:23,252 - __main__ - INFO - Resampling

Patient: MDA-073
(512, 512, 127)

2024-11-11 19:14:31,919 - __main__ - INFO - Resampling

Patient: MDA-124
(512, 512, 119)

2024-11-11 19:14:40,062 - __main__ - INFO - Resampling

Patient: MDA-084
(512, 512, 127)

2024-11-11 19:14:48,740 - __main__ - INFO - Resampling

Patient: MDA-026
(512, 512, 127)

2024-11-11 19:14:57,366 - __main__ - INFO - Resampling

Patient: MDA-158
(512, 512, 127)

2024-11-11 19:15:05,915 - __main__ - INFO - Resampling

Patient: MDA-079
(512, 512, 127)

2024-11-11 19:15:14,263 - __main__ - INFO - Resampling

Patient: MDA-015
(512, 512, 135)

2024-11-11 19:15:23,447 - __main__ - INFO - Resampling

Patient: MDA-029
(512, 512, 302)

2024-11-11 19:15:43,587 - __main__ - INFO - Resampling

Patient: MDA-129
(512, 512, 127)

2024-11-11 19:15:51,955 - __main__ - INFO - Resampling

Round 140: 54.69% completed
Patient: MDA-167
(512, 512, 91)

2024-11-11 19:15:58,077 - __main__ - INFO - Resampling

Patient: MDA-106
(512, 512, 119)

2024-11-11 19:16:06,172 - __main__ - INFO - Resampling

Patient: MDA-177
(512, 512, 127)

2024-11-11 19:16:14,887 - __main__ - INFO - Resampling

Patient: MDA-142
(512, 512, 127)

2024-11-11 19:16:23,208 - __main__ - INFO - Resampling

Patient: MDA-180
(512, 512, 127)

2024-11-11 19:16:31,672 - __main__ - INFO - Resampling

Patient: MDA-171
(512, 512, 91)

2024-11-11 19:16:37,834 - __main__ - INFO - Resampling

Patient: MDA-136
(512, 512, 127)

2024-11-11 19:16:46,287 - __main__ - INFO - Resampling

Patient: MDA-003
(512, 512, 267)

2024-11-11 19:17:04,406 - __main__ - INFO - Resampling

Patient: MDA-028
(512, 512, 127)

2024-11-11 19:17:12,798 - __main__ - INFO - Resampling

Patient: MDA-057
(512, 512, 311)

2024-11-11 19:17:33,756 - __main__ - INFO - Resampling

Round 150: 58.59% completed
Patient: MDA-063
(512, 512, 299)

2024-11-11 19:17:53,688 - __main__ - INFO - Resampling

Patient: MDA-077
(512, 512, 127)

2024-11-11 19:18:02,111 - __main__ - INFO - Resampling

Patient: MDA-107
(512, 512, 119)

2024-11-11 19:18:10,329 - __main__ - INFO - Resampling

Patient: MDA-193
(512, 512, 127)

2024-11-11 19:18:18,528 - __main__ - INFO - Resampling

Patient: MDA-096
(512, 512, 127)

2024-11-11 19:18:26,698 - __main__ - INFO - Resampling

Patient: MDA-074
(512, 512, 337)

2024-11-11 19:18:48,241 - __main__ - INFO - Resampling

Patient: MDA-152
(512, 512, 127)

2024-11-11 19:18:56,708 - __main__ - INFO - Resampling

Patient: MDA-145
(512, 512, 87)

2024-11-11 19:19:02,706 - __main__ - INFO - Resampling

Patient: MDA-198
(512, 512, 127)

2024-11-11 19:19:10,874 - __main__ - INFO - Resampling

Patient: MDA-105
(512, 512, 119)

2024-11-11 19:19:18,827 - __main__ - INFO - Resampling

Round 160: 62.50% completed
Patient: MDA-138
(512, 512, 127)

2024-11-11 19:19:27,466 - __main__ - INFO - Resampling

Patient: MDA-070
(512, 512, 127)

2024-11-11 19:19:36,114 - __main__ - INFO - Resampling

Patient: MDA-014
(512, 512, 91)

2024-11-11 19:19:42,304 - __main__ - INFO - Resampling

Patient: MDA-196
(512, 512, 127)

2024-11-11 19:19:50,764 - __main__ - INFO - Resampling

Patient: MDA-123
(512, 512, 267)

2024-11-11 19:20:08,411 - __main__ - INFO - Resampling

Patient: MDA-170
(512, 512, 311)

2024-11-11 19:20:28,409 - __main__ - INFO - Resampling

Patient: MDA-037
(512, 512, 127)

2024-11-11 19:20:36,651 - __main__ - INFO - Resampling

Patient: MDA-035
(512, 512, 311)

2024-11-11 19:20:57,272 - __main__ - INFO - Resampling

Patient: MDA-104
(512, 512, 119)

2024-11-11 19:21:05,413 - __main__ - INFO - Resampling

Patient: MDA-019
(512, 512, 127)

2024-11-11 19:21:13,656 - __main__ - INFO - Resampling

Round 170: 66.41% completed
Patient: MDA-178
(512, 512, 247)

2024-11-11 19:21:30,254 - __main__ - INFO - Resampling

Patient: MDA-186
(512, 512, 127)

2024-11-11 19:21:38,579 - __main__ - INFO - Resampling

Patient: MDA-126
(512, 512, 127)

2024-11-11 19:21:47,043 - __main__ - INFO - Resampling

Patient: MDA-066
(512, 512, 127)

2024-11-11 19:21:56,517 - __main__ - INFO - Resampling

Patient: MDA-160
(512, 512, 127)

2024-11-11 19:22:04,984 - __main__ - INFO - Resampling

Patient: MDA-122
(512, 512, 298)

2024-11-11 19:22:25,293 - __main__ - INFO - Resampling

Patient: MDA-135
(512, 512, 127)

2024-11-11 19:22:33,821 - __main__ - INFO - Resampling

Patient: MDA-201
(512, 512, 127)

2024-11-11 19:22:42,589 - __main__ - INFO - Resampling

Patient: MDA-115
(512, 512, 127)

2024-11-11 19:22:51,004 - __main__ - INFO - Resampling

Patient: MDA-036
(512, 512, 267)

2024-11-11 19:23:09,053 - __main__ - INFO - Resampling

Round 180: 70.31% completed
Patient: MDA-072
(512, 512, 311)

2024-11-11 19:23:29,970 - __main__ - INFO - Resampling

Patient: MDA-094
(512, 512, 127)

2024-11-11 19:23:38,293 - __main__ - INFO - Resampling

Patient: MDA-140
(512, 512, 127)

2024-11-11 19:23:46,627 - __main__ - INFO - Resampling

Patient: CHUP-016
(512, 512, 260)

2024-11-11 19:24:08,611 - __main__ - INFO - Resampling

Patient: CHUP-003
(512, 512, 298)

2024-11-11 19:24:33,791 - __main__ - INFO - Resampling

Patient: CHUP-017
(512, 512, 298)

2024-11-11 19:24:59,173 - __main__ - INFO - Resampling

Patient: CHUP-041
(512, 512, 298)

2024-11-11 19:25:24,073 - __main__ - INFO - Resampling

Patient: CHUP-037
(512, 512, 298)

2024-11-11 19:25:49,674 - __main__ - INFO - Resampling

Patient: CHUP-010
(512, 512, 298)

2024-11-11 19:26:15,632 - __main__ - INFO - Resampling

Patient: CHUP-050
(512, 512, 298)

2024-11-11 19:26:41,069 - __main__ - INFO - Resampling

Round 190: 74.22% completed
Patient: CHUP-068
(512, 512, 298)

2024-11-11 19:27:06,169 - __main__ - INFO - Resampling

Patient: CHUP-026
(512, 512, 298)

2024-11-11 19:27:32,130 - __main__ - INFO - Resampling

Patient: CHUP-018
(512, 512, 260)

2024-11-11 19:27:54,743 - __main__ - INFO - Resampling

Patient: CHUP-043
(512, 512, 298)

2024-11-11 19:28:20,423 - __main__ - INFO - Resampling

Patient: CHUP-060
(512, 512, 260)

2024-11-11 19:28:43,562 - __main__ - INFO - Resampling

Patient: CHUP-036
(512, 512, 260)

2024-11-11 19:29:05,669 - __main__ - INFO - Resampling

Patient: CHUP-062
(512, 512, 298)

2024-11-11 19:29:31,339 - __main__ - INFO - Resampling

Patient: CHUP-039
(512, 512, 260)

2024-11-11 19:29:53,325 - __main__ - INFO - Resampling

Patient: CHUP-064
(512, 512, 260)

2024-11-11 19:30:15,973 - __main__ - INFO - Resampling

Patient: CHUP-073
(512, 512, 260)

2024-11-11 19:30:38,344 - __main__ - INFO - Resampling

Round 200: 78.12% completed
Patient: CHUP-066
(512, 512, 298)

2024-11-11 19:31:03,964 - __main__ - INFO - Resampling

Patient: CHUP-034
(512, 512, 260)

2024-11-11 19:31:26,460 - __main__ - INFO - Resampling

Patient: CHUP-059
(512, 512, 298)

2024-11-11 19:31:51,665 - __main__ - INFO - Resampling

Patient: CHUP-058
(512, 512, 337)

2024-11-11 19:32:20,626 - __main__ - INFO - Resampling

Patient: CHUP-008
(512, 512, 337)

2024-11-11 19:32:49,127 - __main__ - INFO - Resampling

Patient: CHUP-070
(512, 512, 298)

2024-11-11 19:33:15,133 - __main__ - INFO - Resampling

Patient: CHUP-071
(512, 512, 298)

2024-11-11 19:33:41,155 - __main__ - INFO - Resampling

Patient: CHUP-040
(512, 512, 260)

2024-11-11 19:34:03,767 - __main__ - INFO - Resampling

Patient: CHUP-011
(512, 512, 260)

2024-11-11 19:34:26,539 - __main__ - INFO - Resampling

Patient: CHUP-033
(512, 512, 298)

2024-11-11 19:34:52,088 - __main__ - INFO - Resampling

Round 210: 82.03% completed
Patient: CHUP-056
(512, 512, 298)

2024-11-11 19:35:17,826 - __main__ - INFO - Resampling

Patient: CHUP-046
(512, 512, 298)

2024-11-11 19:35:43,350 - __main__ - INFO - Resampling

Patient: CHUP-025
(512, 512, 298)

2024-11-11 19:36:09,136 - __main__ - INFO - Resampling

Patient: CHUP-048
(512, 512, 260)

2024-11-11 19:36:32,337 - __main__ - INFO - Resampling

Patient: CHUP-049
(512, 512, 337)

2024-11-11 19:37:02,244 - __main__ - INFO - Resampling

Patient: CHUP-065
(512, 512, 298)

2024-11-11 19:37:28,032 - __main__ - INFO - Resampling

Patient: CHUP-023
(512, 512, 298)

2024-11-11 19:37:53,161 - __main__ - INFO - Resampling

Patient: CHUP-055
(512, 512, 260)

2024-11-11 19:38:15,503 - __main__ - INFO - Resampling

Patient: CHUP-053
(512, 512, 260)

2024-11-11 19:38:38,234 - __main__ - INFO - Resampling

Patient: CHUP-063
(512, 512, 298)

2024-11-11 19:39:03,782 - __main__ - INFO - Resampling

Round 220: 85.94% completed
Patient: CHUP-013
(512, 512, 260)

2024-11-11 19:39:25,906 - __main__ - INFO - Resampling

Patient: CHUP-044
(512, 512, 298)

2024-11-11 19:39:51,497 - __main__ - INFO - Resampling

Patient: CHUP-019
(512, 512, 260)

2024-11-11 19:40:13,960 - __main__ - INFO - Resampling

Patient: CHUP-074
(512, 512, 260)

2024-11-11 19:40:36,178 - __main__ - INFO - Resampling

Patient: CHUP-022
(512, 512, 298)

2024-11-11 19:41:01,620 - __main__ - INFO - Resampling

Patient: CHUP-002
(512, 512, 298)

2024-11-11 19:41:27,116 - __main__ - INFO - Resampling

Patient: CHUP-000
(512, 512, 260)

2024-11-11 19:41:49,696 - __main__ - INFO - Resampling

Patient: CHUP-024
(512, 512, 298)

2024-11-11 19:42:15,718 - __main__ - INFO - Resampling

Patient: CHUP-035
(512, 512, 298)

2024-11-11 19:42:40,796 - __main__ - INFO - Resampling

Patient: CHUP-028
(512, 512, 260)

2024-11-11 19:43:02,905 - __main__ - INFO - Resampling

Round 230: 89.84% completed
Patient: CHUP-032
(512, 512, 260)

2024-11-11 19:43:25,578 - __main__ - INFO - Resampling

Patient: CHUP-007
(512, 512, 260)

2024-11-11 19:43:47,618 - __main__ - INFO - Resampling

Patient: CHUP-015
(512, 512, 221)

2024-11-11 19:44:07,100 - __main__ - INFO - Resampling

Patient: CHUP-054
(512, 512, 260)

2024-11-11 19:44:29,398 - __main__ - INFO - Resampling

Patient: CHUP-005
(512, 512, 298)

2024-11-11 19:44:54,614 - __main__ - INFO - Resampling

Patient: CHUP-072
(512, 512, 260)

2024-11-11 19:45:17,408 - __main__ - INFO - Resampling

Patient: CHUP-009
(512, 512, 298)

2024-11-11 19:45:43,769 - __main__ - INFO - Resampling

Patient: CHUP-057
(512, 512, 298)

2024-11-11 19:46:09,733 - __main__ - INFO - Resampling

Patient: CHUP-001
(512, 512, 260)

2024-11-11 19:46:32,043 - __main__ - INFO - Resampling

Patient: CHUP-004
(512, 512, 298)

2024-11-11 19:46:57,659 - __main__ - INFO - Resampling

Round 240: 93.75% completed
Patient: CHUP-006
(512, 512, 260)

2024-11-11 19:47:20,757 - __main__ - INFO - Resampling

Patient: CHUP-067
(512, 512, 260)

2024-11-11 19:47:43,841 - __main__ - INFO - Resampling

Patient: CHUP-042
(512, 512, 298)

2024-11-11 19:48:09,491 - __main__ - INFO - Resampling

Patient: CHUP-075
(512, 512, 260)

2024-11-11 19:48:31,206 - __main__ - INFO - Resampling

Patient: CHUP-047
(512, 512, 337)

2024-11-11 19:49:00,664 - __main__ - INFO - Resampling

Patient: CHUP-029
(512, 512, 260)

2024-11-11 19:49:23,127 - __main__ - INFO - Resampling

Patient: CHUP-012
(512, 512, 298)

2024-11-11 19:49:48,947 - __main__ - INFO - Resampling

Patient: CHUP-020
(512, 512, 298)

2024-11-11 19:50:15,031 - __main__ - INFO - Resampling

Patient: CHUP-051
(512, 512, 298)

2024-11-11 19:50:40,269 - __main__ - INFO - Resampling

Patient: CHUP-069
(512, 512, 260)

2024-11-11 19:51:02,584 - __main__ - INFO - Resampling

Round 250: 97.66% completed
Patient: CHUP-027
(512, 512, 337)

2024-11-11 19:51:31,770 - __main__ - INFO - Resampling

Patient: CHUP-030
(512, 512, 337)

2024-11-11 19:52:00,622 - __main__ - INFO - Resampling

Patient: CHUP-038
(512, 512, 260)

2024-11-11 19:52:22,509 - __main__ - INFO - Resampling

Patient: CHUP-052
(512, 512, 260)

2024-11-11 19:52:44,634 - __main__ - INFO - Resampling

Patient: CHUP-061
(512, 512, 298)

# Sandbox

In [56]:
show_ct_data(apply_window(x.get_fdata()))

interactive(children=(IntSlider(value=0, description='slice_idx', max=735), Output()), _dom_classes=('widget-i…

In [52]:
# Call the main function to start resampling (one patient)
patient = 'CHUP-030' # patient_list[3]
print(patient)
c, p, l = main(patient, input_image_folder, input_label_folder, output_image_folder, output_label_folder, cores, resampling)

2024-11-09 11:21:23,344 - __main__ - INFO - Resampling

CHUP-030

In [62]:
cn = apply_window(sitk.GetArrayFromImage(c))
pn = sitk.GetArrayFromImage(p)
ln = sitk.GetArrayFromImage(l)
print(cn.shape, pn.shape, ln.shape)

(337, 512, 512) (337, 512, 512) (337, 512, 512)

In [63]:
pn_r = np.rot90(pn, axes=(0,2))
cn_r = np.rot90(cn, axes=(0,2))
ln_r = np.rot90(ln, axes=(0,2))

In [64]:
show_ct_data_with_labels(cn_r, ln_r)

interactive(children=(IntSlider(value=0, description='slice_idx', max=336), Output()), _dom_classes=('widget-i…

In [56]:
show_ct_data_with_labels(pn, ln)

interactive(children=(IntSlider(value=0, description='slice_idx', max=460), Output()), _dom_classes=('widget-i…

In [87]:
import pandas as pd

In [88]:
df = pd.read_csv('../../datasets/ADDA/png_patches_2d/png_patch_training_file_with_tags.csv')
df.head()

,subject_id,dataset,set,ct_path,pet_path,label_path,not_black_frame,tumor
0,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0
1,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0
2,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0
3,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0
4,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0

In [92]:
df['dataset'].unique()

array(['source', 'target'], dtype=object)

In [95]:
df[df['set'] == 'train']['subject_id'].unique()

array(['MDA-039', 'MDA-192', 'MDA-187', 'MDA-179', 'MDA-162', 'MDA-097',
       'MDA-194', 'MDA-095', 'MDA-038', 'MDA-147', 'MDA-150', 'MDA-133',
       'MDA-071', 'MDA-113', 'MDA-023', 'MDA-024', 'MDA-013', 'MDA-059',
       'MDA-006', 'MDA-101', 'MDA-065', 'MDA-120', 'MDA-163', 'MDA-064',
       'MDA-025', 'MDA-088', 'MDA-098', 'MDA-099', 'MDA-078', 'MDA-020',
       'MDA-100', 'MDA-021', 'MDA-005', 'MDA-047', 'MDA-173', 'MDA-146',
       'MDA-068', 'MDA-053', 'MDA-004', 'MDA-114', 'MDA-055', 'MDA-061',
       'MDA-132', 'MDA-164', 'MDA-159', 'MDA-172', 'MDA-143', 'MDA-175',
       'MDA-076', 'MDA-139', 'MDA-018', 'MDA-112', 'MDA-048', 'MDA-117',
       'MDA-043', 'MDA-169', 'MDA-050', 'MDA-190', 'MDA-049', 'MDA-091',
       'MDA-045', 'MDA-067', 'MDA-058', 'MDA-134', 'MDA-082', 'MDA-148',
       'MDA-027', 'MDA-011', 'MDA-121', 'MDA-144', 'MDA-156', 'MDA-184',
       'MDA-183', 'MDA-093', 'MDA-016', 'MDA-092', 'MDA-116', 'MDA-034',
       'MDA-155', 'MDA-108', 'MDA-044', 'MDA-083', 'MDA-089', 'MDA-118',
       'MDA-041', 'MDA-046', 'MDA-040', 'MDA-007', 'MDA-110', 'MDA-069',
       'MDA-109', 'MDA-137', 'MDA-075', 'MDA-111', 'MDA-080', 'MDA-081',
       'MDA-022', 'MDA-181', 'MDA-056', 'MDA-017', 'MDA-087', 'MDA-012',
       'MDA-174', 'MDA-042', 'MDA-030', 'MDA-191', 'MDA-182', 'MDA-085',
       'MDA-166', 'MDA-054', 'MDA-131', 'MDA-189', 'MDA-154', 'MDA-151',
       'MDA-090', 'MDA-165', 'MDA-060', 'MDA-125', 'MDA-197', 'MDA-130',
       'MDA-141', 'MDA-188', 'MDA-200', 'MDA-199', 'MDA-051', 'MDA-062',
       'MDA-128', 'MDA-102', 'CHUP-016', 'CHUP-003', 'CHUP-017',
       'CHUP-041', 'CHUP-037', 'CHUP-010', 'CHUP-050', 'CHUP-068',
       'CHUP-026', 'CHUP-018', 'CHUP-043', 'CHUP-060', 'CHUP-036',
       'CHUP-062', 'CHUP-039', 'CHUP-064', 'CHUP-073', 'CHUP-066',
       'CHUP-034', 'CHUP-059', 'CHUP-058', 'CHUP-008', 'CHUP-070',
       'CHUP-071', 'CHUP-040', 'CHUP-011', 'CHUP-033', 'CHUP-056',
       'CHUP-046', 'CHUP-025', 'CHUP-048', 'CHUP-049', 'CHUP-065',
       'CHUP-023', 'CHUP-055', 'CHUP-053', 'CHUP-063', 'CHUP-013',
       'CHUP-044', 'CHUP-019', 'CHUP-074', 'CHUP-022', 'CHUP-002',
       'CHUP-000', 'CHUP-024', 'CHUP-035', 'CHUP-028', 'CHUP-032',
       'CHUP-007', 'CHUP-015'], dtype=object)

## Create a beakdown df for the new dataset

In [5]:
import pandas as pd
import os

In [6]:
path_data_breakdown = '../../datasets/ADDA/png_patches_2d/png_patch_training_file_with_tags.csv'
images_path = "/Volumes/Seagate/Research/ADDA/resampled_subsets/images"
labels_path = "/Volumes/Seagate/Research/ADDA/resampled_subsets/labels"

In [4]:
# load the previous file
df = pd.read_csv(path_data_breakdown)
# df = df[['subject_id', 'dataset', 'set']]
df.head()

,subject_id,dataset,set,ct_path,pet_path,label_path,not_black_frame,tumor
0,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0
1,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0
2,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0
3,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0
4,MDA-039,source,train,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/images/MDA-039...,../datasets/ADDA/png_patches_2d/labels/MDA-039...,0,0

In [22]:
# create an empty df
img_data = pd.DataFrame({
    'subject_id': []
})

In [24]:
# get all the image names from the folder
subject_ids = [x.split('_')[0] for x in os.listdir(images_path)]
img_data['subject_id'] = subject_ids
img_data.head()

  subject_id
0    MDA-039
1    MDA-039
2    MDA-192
3    MDA-192
4    MDA-187

In [32]:
# get the dataset and set for each image
img_data = pd.merge(img_data, df[['subject_id', 'set', 'dataset']], left_on='subject_id', right_on='subject_id' , how='inner')

In [36]:
# remove duplicates
img_data = img_data[~img_data.duplicated()]

In [38]:
img_data.head()

      subject_id    set dataset
0        MDA-039  train  source
9800     MDA-192  train  source
19600    MDA-187  train  source
29400    MDA-179  train  source
39200    MDA-162  train  source

In [39]:
img_data.groupby(['dataset', 'set']).subject_id.nunique().reset_index()

  dataset         set  subject_id
0  source        test          28
1  source       train         128
2  source  validation          28
3  target        test          15
4  target       train          50
5  target  validation           7

In [40]:
save_path = "/Volumes/Seagate/Research/ADDA/resampled_subsets"
img_data.to_csv(os.path.join(save_path, 'dataset.csv'), index=False)

# Sandbox

In [46]:
print(df['pet_path'][0])
print(df['ct_path'][0])
print(df['label_path'][0])

../datasets/ADDA/png_patches_2d/images/MDA-039__PT_0_0_0.png
../datasets/ADDA/png_patches_2d/images/MDA-039__CT_0_0_0.png
../datasets/ADDA/png_patches_2d/labels/MDA-039_0_0_0.png

In [ ]:

# Define paths for input images, labels, and output directories
path_input_images = "../datasets/ADDA/original/images"
path_input_labels = "../datasets/ADDA/original/labels"
path_output_images = "../datasets/ADDA/resampled/images"
path_output_labels = "../datasets/ADDA/resampled/labels"

# Setting up logger to capture information and warnings
log_fmt = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
logging.basicConfig(level=logging.INFO, format=log_fmt)
logging.captureWarnings(True)
logger = logging.getLogger(__name__)

# Function to get bounding boxes from CT and PT images
def get_bounding_boxes(ct, pt):
    """
    Get the bounding boxes of the CT and PT images.
    This works since all images have the same direction.
    """
    
    # Get the origins of both CT and PT images
    ct_origin = np.array(ct.GetOrigin())
    pt_origin = np.array(pt.GetOrigin())
    
    # Calculate the maximum positions for both CT and PT images
    ct_position_max = ct_origin + np.array(ct.GetSize()) * np.array(ct.GetSpacing())
    pt_position_max = pt_origin + np.array(pt.GetSize()) * np.array(pt.GetSpacing())
    
    # Return the combined bounding box that covers both images
    return np.concatenate([
        np.maximum(ct_origin, pt_origin),
        np.minimum(ct_position_max, pt_position_max),
    ], axis=0)

# Main function to perform resampling
def main(input_image_folder, input_label_folder, output_image_folder,
         output_label_folder, cores, resampling):
    """Resamples NIFTI files within the maximal bounding box covered by both modalities (PT and CT)."""
    
    logger.info('Resampling')

    # Resolve paths to absolute paths
    input_image_folder = Path(input_image_folder).resolve()
    input_label_folder = Path(input_label_folder).resolve()
    output_image_folder = Path(output_image_folder).resolve()
    output_label_folder = Path(output_label_folder).resolve()

    # Create output folders if they do not exist
    output_image_folder.mkdir(exist_ok=True)
    output_label_folder.mkdir(exist_ok=True)
    print('Resampling with voxel size: {}'.format(resampling))

    # Get list of patients by finding CT images in the input folder
    patient_list = [
        f.name.split("__")[0] for f in input_image_folder.rglob("*_CT*")
    ]
    if len(patient_list) == 0:
        raise ValueError("No patient found in the input folder")

    # Initialize the resampler with default settings
    resampler = sitk.ResampleImageFilter()
    resampler.SetOutputDirection([1, 0, 0, 0, 1, 0, 0, 0, 1])
    resampler.SetOutputSpacing(resampling)

    # Define the function to resample one patient's images and labels
    def resample_one_patient(p):
        # Read CT and PT images for the patient
        ct = sitk.ReadImage(str([f for f in input_image_folder.rglob(p + "__CT*")][0]))
        pt = sitk.ReadImage(str([f for f in input_image_folder.rglob(p + "__PT*")][0]))
        
        # Read label images for the patient
        labels = [(sitk.ReadImage(str(f)), f.name) for f in input_label_folder.glob(p + "*")]
        
        # Get bounding box for the resampling operation
        bb = get_bounding_boxes(ct, pt)
        size = np.round((bb[3:] - bb[:3]) / resampling).astype(int)
        
        # Configure resampler settings for CT and PT images
        resampler.SetOutputOrigin(bb[:3])
        resampler.SetSize([int(k) for k in size])
        resampler.SetInterpolator(sitk.sitkBSpline)  # Use cubic spline interpolation for CT and PT
        
        # Resample CT and PT images
        ct = resampler.Execute(ct)
        pt = resampler.Execute(pt)
        
        # Save the resampled CT and PT images to the output folder
        sitk.WriteImage(ct, str((output_image_folder / (p + "__CT.nii.gz"))))
        sitk.WriteImage(pt, str((output_image_folder / (p + "__PT.nii.gz"))))
        
        # Configure resampler for label images using nearest neighbor interpolation
        resampler.SetInterpolator(sitk.sitkNearestNeighbor)
        for label, name in labels:
            label = resampler.Execute(label)
            sitk.WriteImage(label, str((output_label_folder / name)))

    # Loop through each patient and resample their images and labels
    for p in patient_list:
        resample_one_patient(p)
    # Uncomment for parallel processing to speed up the operation
    # with Pool(cores) as p:
    #     p.map(resample_one_patient, patient_list)

# Execute the main function with example parameters
input_image_folder = path_input_images
input_label_folder = path_input_labels
output_image_folder = path_output_images
output_label_folder = path_output_labels
cores = 12
resampling = (2, 2, 2)

# Call the main function to start resampling
main(input_image_folder, input_label_folder, output_image_folder, output_label_folder, cores, resampling)